#ifndef __KERNEL_ARCH_X86_ISR_H__
#define __KERNEL_ARCH_X86_ISR_H__

void irq_handler_0();
void irq_handler_1();
void irq_handler_2();
void irq_handler_3();
void irq_handler_4();
void irq_handler_5();
void irq_handler_6();
void irq_handler_7();
void irq_handler_8();
void irq_handler_9();
void irq_handler_10();
void irq_handler_11();
void irq_handler_12();
void irq_handler_13();
void irq_handler_14();
void irq_handler_15();
void isr_handler_exception();
void isr_handler_exception_0();
void isr_handler_exception_1();
void isr_handler_exception_2();
void isr_handler_exception_3();
void isr_handler_exception_4();
void isr_handler_exception_5();
void isr_handler_exception_6();
void isr_handler_exception_7();
void isr_handler_exception_8();
void isr_handler_exception_9();
void isr_handler_exception_10();
void isr_handler_exception_11();
void isr_handler_exception_12();
void isr_handler_exception_13();
void isr_handler_exception_14();
void isr_handler_exception_15();
void isr_handler_exception_16();
void isr_handler_exception_17();
void isr_handler_exception_18();
void isr_handler_exception_19();
void isr_handler_exception_20();
void isr_handler_exception_21();
void isr_handler_exception_22();
void isr_handler_exception_23();
void isr_handler_exception_24();
void isr_handler_exception_25();
void isr_handler_exception_26();
void isr_handler_exception_27();
void isr_handler_exception_28();
void isr_handler_exception_29();
void isr_handler_exception_30();
void isr_handler_exception_31();
void isr_syscall();

#endif