#ifndef __INCLUDE_ARCH_AMD64_ISR_H__
#define __INCLUDE_ARCH_AMD64_ISR_H__

#include <stddef.h>
#include <stdint.h>

void isr_exception0(void);
void isr_exception1(void);
void isr_exception2(void);
void isr_exception3(void);
void isr_exception4(void);
void isr_exception5(void);
void isr_exception6(void);
void isr_exception7(void);
void isr_exception8(void);
void isr_exception9(void);
void isr_exception10(void);
void isr_exception11(void);
void isr_exception12(void);
void isr_exception13(void);
void isr_exception14(void);
void isr_exception15(void);
void isr_exception16(void);
void isr_exception17(void);
void isr_exception18(void);
void isr_exception19(void);
void isr_exception20(void);
void isr_exception21(void);
void isr_exception22(void);
void isr_exception23(void);
void isr_exception24(void);
void isr_exception25(void);
void isr_exception26(void);
void isr_exception27(void);
void isr_exception28(void);
void isr_exception29(void);
void isr_exception30(void);
void isr_exception31(void);
void isr_irq0(void);
void isr_irq1(void);
void isr_irq2(void);
void isr_irq3(void);
void isr_irq4(void);
void isr_irq5(void);
void isr_irq6(void);
void isr_irq7(void);
void isr_irq8(void);
void isr_irq9(void);
void isr_irq10(void);
void isr_irq11(void);
void isr_irq12(void);
void isr_irq13(void);
void isr_irq14(void);
void isr_irq15(void);

#endif
